// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: common/service.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackendType int32

const (
	BackendType_XRAY      BackendType = 0
	BackendType_WIREGUARD BackendType = 1
)

// Enum value maps for BackendType.
var (
	BackendType_name = map[int32]string{
		0: "XRAY",
		1: "WIREGUARD",
	}
	BackendType_value = map[string]int32{
		"XRAY":      0,
		"WIREGUARD": 1,
	}
)

func (x BackendType) Enum() *BackendType {
	p := new(BackendType)
	*p = x
	return p
}

func (x BackendType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackendType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_service_proto_enumTypes[0].Descriptor()
}

func (BackendType) Type() protoreflect.EnumType {
	return &file_common_service_proto_enumTypes[0]
}

func (x BackendType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackendType.Descriptor instead.
func (BackendType) EnumDescriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{0}
}

type StatType int32

const (
	StatType_Outbounds StatType = 0
	StatType_Outbound  StatType = 1
	StatType_Inbounds  StatType = 2
	StatType_Inbound   StatType = 3
	StatType_UsersStat StatType = 4
	StatType_UserStat  StatType = 5
)

// Enum value maps for StatType.
var (
	StatType_name = map[int32]string{
		0: "Outbounds",
		1: "Outbound",
		2: "Inbounds",
		3: "Inbound",
		4: "UsersStat",
		5: "UserStat",
	}
	StatType_value = map[string]int32{
		"Outbounds": 0,
		"Outbound":  1,
		"Inbounds":  2,
		"Inbound":   3,
		"UsersStat": 4,
		"UserStat":  5,
	}
)

func (x StatType) Enum() *StatType {
	p := new(StatType)
	*p = x
	return p
}

func (x StatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_service_proto_enumTypes[1].Descriptor()
}

func (StatType) Type() protoreflect.EnumType {
	return &file_common_service_proto_enumTypes[1]
}

func (x StatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatType.Descriptor instead.
func (StatType) EnumDescriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_common_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{0}
}

// Base info response message
type BaseInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	CoreVersion   string                 `protobuf:"bytes,2,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"`
	NodeVersion   string                 `protobuf:"bytes,3,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseInfoResponse) Reset() {
	*x = BaseInfoResponse{}
	mi := &file_common_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseInfoResponse) ProtoMessage() {}

func (x *BaseInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseInfoResponse.ProtoReflect.Descriptor instead.
func (*BaseInfoResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{1}
}

func (x *BaseInfoResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *BaseInfoResponse) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *BaseInfoResponse) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

type Backend struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            BackendType            `protobuf:"varint,1,opt,name=type,proto3,enum=service.BackendType" json:"type,omitempty"`
	Config          string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Users           []*User                `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	KeepAlive       uint64                 `protobuf:"varint,4,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
	ExcludeInbounds []string               `protobuf:"bytes,5,rep,name=exclude_inbounds,json=excludeInbounds,proto3" json:"exclude_inbounds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_common_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{2}
}

func (x *Backend) GetType() BackendType {
	if x != nil {
		return x.Type
	}
	return BackendType_XRAY
}

func (x *Backend) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Backend) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Backend) GetKeepAlive() uint64 {
	if x != nil {
		return x.KeepAlive
	}
	return 0
}

func (x *Backend) GetExcludeInbounds() []string {
	if x != nil {
		return x.ExcludeInbounds
	}
	return nil
}

// log
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        string                 `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_common_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{3}
}

func (x *Log) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// stats
type Stat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Value         int64                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_common_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{4}
}

func (x *Stat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Stat) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Stat) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*Stat                `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_common_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{5}
}

func (x *StatResponse) GetStats() []*Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Reset_        bool                   `protobuf:"varint,2,opt,name=reset,proto3" json:"reset,omitempty"`
	Type          StatType               `protobuf:"varint,3,opt,name=type,proto3,enum=service.StatType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_common_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{6}
}

func (x *StatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

func (x *StatRequest) GetType() StatType {
	if x != nil {
		return x.Type
	}
	return StatType_Outbounds
}

type OnlineStatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineStatResponse) Reset() {
	*x = OnlineStatResponse{}
	mi := &file_common_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineStatResponse) ProtoMessage() {}

func (x *OnlineStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineStatResponse.ProtoReflect.Descriptor instead.
func (*OnlineStatResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{7}
}

func (x *OnlineStatResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OnlineStatResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StatsOnlineIpListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ips           map[string]int64       `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsOnlineIpListResponse) Reset() {
	*x = StatsOnlineIpListResponse{}
	mi := &file_common_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsOnlineIpListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsOnlineIpListResponse) ProtoMessage() {}

func (x *StatsOnlineIpListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsOnlineIpListResponse.ProtoReflect.Descriptor instead.
func (*StatsOnlineIpListResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{8}
}

func (x *StatsOnlineIpListResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatsOnlineIpListResponse) GetIps() map[string]int64 {
	if x != nil {
		return x.Ips
	}
	return nil
}

// Bulk online status for ALL users in one call - wraps xray-core's native
// StatsService.GetAllOnlineUsers (app/stats/command/command.proto upstream),
// which returns every currently-online "user>>>{email}>>>online" metric name
// in one round trip. We strip the xray-specific prefix/suffix node-side and
// hand back clean emails, so the panel never needs per-email RPCs just to
// find out who's online right now.
type UsersOnlineStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersOnlineStatsRequest) Reset() {
	*x = UsersOnlineStatsRequest{}
	mi := &file_common_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersOnlineStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersOnlineStatsRequest) ProtoMessage() {}

func (x *UsersOnlineStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersOnlineStatsRequest.ProtoReflect.Descriptor instead.
func (*UsersOnlineStatsRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{9}
}

type UsersOnlineStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []string               `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersOnlineStatsResponse) Reset() {
	*x = UsersOnlineStatsResponse{}
	mi := &file_common_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersOnlineStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersOnlineStatsResponse) ProtoMessage() {}

func (x *UsersOnlineStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersOnlineStatsResponse.ProtoReflect.Descriptor instead.
func (*UsersOnlineStatsResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{10}
}

func (x *UsersOnlineStatsResponse) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

type Latency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Alive         bool                   `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
	Delay         int64                  `protobuf:"varint,3,opt,name=delay,proto3" json:"delay,omitempty"`
	Link          string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	LastSeenTime  int64                  `protobuf:"varint,5,opt,name=last_seen_time,json=lastSeenTime,proto3" json:"last_seen_time,omitempty"`
	LastTryTime   int64                  `protobuf:"varint,6,opt,name=last_try_time,json=lastTryTime,proto3" json:"last_try_time,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Latency) Reset() {
	*x = Latency{}
	mi := &file_common_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Latency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Latency) ProtoMessage() {}

func (x *Latency) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Latency.ProtoReflect.Descriptor instead.
func (*Latency) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{11}
}

func (x *Latency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Latency) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *Latency) GetDelay() int64 {
	if x != nil {
		return x.Delay
	}
	return 0
}

func (x *Latency) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Latency) GetLastSeenTime() int64 {
	if x != nil {
		return x.LastSeenTime
	}
	return 0
}

func (x *Latency) GetLastTryTime() int64 {
	if x != nil {
		return x.LastTryTime
	}
	return 0
}

func (x *Latency) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type LatencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyRequest) Reset() {
	*x = LatencyRequest{}
	mi := &file_common_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyRequest) ProtoMessage() {}

func (x *LatencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyRequest.ProtoReflect.Descriptor instead.
func (*LatencyRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{12}
}

func (x *LatencyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LatencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latencies     []*Latency             `protobuf:"bytes,1,rep,name=latencies,proto3" json:"latencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyResponse) Reset() {
	*x = LatencyResponse{}
	mi := &file_common_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyResponse) ProtoMessage() {}

func (x *LatencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyResponse.ProtoReflect.Descriptor instead.
func (*LatencyResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{13}
}

func (x *LatencyResponse) GetLatencies() []*Latency {
	if x != nil {
		return x.Latencies
	}
	return nil
}

type BackendStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumGoroutine  uint32                 `protobuf:"varint,1,opt,name=num_goroutine,json=numGoroutine,proto3" json:"num_goroutine,omitempty"`
	NumGc         uint32                 `protobuf:"varint,2,opt,name=num_gc,json=numGc,proto3" json:"num_gc,omitempty"`
	Alloc         uint64                 `protobuf:"varint,3,opt,name=alloc,proto3" json:"alloc,omitempty"`
	TotalAlloc    uint64                 `protobuf:"varint,4,opt,name=total_alloc,json=totalAlloc,proto3" json:"total_alloc,omitempty"`
	Sys           uint64                 `protobuf:"varint,5,opt,name=sys,proto3" json:"sys,omitempty"`
	Mallocs       uint64                 `protobuf:"varint,6,opt,name=mallocs,proto3" json:"mallocs,omitempty"`
	Frees         uint64                 `protobuf:"varint,7,opt,name=frees,proto3" json:"frees,omitempty"`
	LiveObjects   uint64                 `protobuf:"varint,8,opt,name=live_objects,json=liveObjects,proto3" json:"live_objects,omitempty"`
	PauseTotalNs  uint64                 `protobuf:"varint,9,opt,name=pause_total_ns,json=pauseTotalNs,proto3" json:"pause_total_ns,omitempty"`
	Uptime        uint32                 `protobuf:"varint,10,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendStatsResponse) Reset() {
	*x = BackendStatsResponse{}
	mi := &file_common_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendStatsResponse) ProtoMessage() {}

func (x *BackendStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendStatsResponse.ProtoReflect.Descriptor instead.
func (*BackendStatsResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{14}
}

func (x *BackendStatsResponse) GetNumGoroutine() uint32 {
	if x != nil {
		return x.NumGoroutine
	}
	return 0
}

func (x *BackendStatsResponse) GetNumGc() uint32 {
	if x != nil {
		return x.NumGc
	}
	return 0
}

func (x *BackendStatsResponse) GetAlloc() uint64 {
	if x != nil {
		return x.Alloc
	}
	return 0
}

func (x *BackendStatsResponse) GetTotalAlloc() uint64 {
	if x != nil {
		return x.TotalAlloc
	}
	return 0
}

func (x *BackendStatsResponse) GetSys() uint64 {
	if x != nil {
		return x.Sys
	}
	return 0
}

func (x *BackendStatsResponse) GetMallocs() uint64 {
	if x != nil {
		return x.Mallocs
	}
	return 0
}

func (x *BackendStatsResponse) GetFrees() uint64 {
	if x != nil {
		return x.Frees
	}
	return 0
}

func (x *BackendStatsResponse) GetLiveObjects() uint64 {
	if x != nil {
		return x.LiveObjects
	}
	return 0
}

func (x *BackendStatsResponse) GetPauseTotalNs() uint64 {
	if x != nil {
		return x.PauseTotalNs
	}
	return 0
}

func (x *BackendStatsResponse) GetUptime() uint32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type SystemStatsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	MemTotal               uint64                 `protobuf:"varint,1,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemUsed                uint64                 `protobuf:"varint,2,opt,name=mem_used,json=memUsed,proto3" json:"mem_used,omitempty"`
	CpuCores               uint64                 `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuUsage               float64                `protobuf:"fixed64,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	IncomingBandwidthSpeed uint64                 `protobuf:"varint,5,opt,name=incoming_bandwidth_speed,json=incomingBandwidthSpeed,proto3" json:"incoming_bandwidth_speed,omitempty"`
	OutgoingBandwidthSpeed uint64                 `protobuf:"varint,6,opt,name=outgoing_bandwidth_speed,json=outgoingBandwidthSpeed,proto3" json:"outgoing_bandwidth_speed,omitempty"`
	Uptime                 uint64                 `protobuf:"varint,7,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SystemStatsResponse) Reset() {
	*x = SystemStatsResponse{}
	mi := &file_common_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatsResponse) ProtoMessage() {}

func (x *SystemStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatsResponse.ProtoReflect.Descriptor instead.
func (*SystemStatsResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{15}
}

func (x *SystemStatsResponse) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *SystemStatsResponse) GetMemUsed() uint64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *SystemStatsResponse) GetCpuCores() uint64 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemStatsResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemStatsResponse) GetIncomingBandwidthSpeed() uint64 {
	if x != nil {
		return x.IncomingBandwidthSpeed
	}
	return 0
}

func (x *SystemStatsResponse) GetOutgoingBandwidthSpeed() uint64 {
	if x != nil {
		return x.OutgoingBandwidthSpeed
	}
	return 0
}

func (x *SystemStatsResponse) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

// User
type Vmess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vmess) Reset() {
	*x = Vmess{}
	mi := &file_common_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vmess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vmess) ProtoMessage() {}

func (x *Vmess) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vmess.ProtoReflect.Descriptor instead.
func (*Vmess) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{16}
}

func (x *Vmess) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Vless struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Flow          string                 `protobuf:"bytes,2,opt,name=flow,proto3" json:"flow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vless) Reset() {
	*x = Vless{}
	mi := &file_common_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vless) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vless) ProtoMessage() {}

func (x *Vless) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vless.ProtoReflect.Descriptor instead.
func (*Vless) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{17}
}

func (x *Vless) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vless) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

type Trojan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trojan) Reset() {
	*x = Trojan{}
	mi := &file_common_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trojan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trojan) ProtoMessage() {}

func (x *Trojan) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trojan.ProtoReflect.Descriptor instead.
func (*Trojan) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{18}
}

func (x *Trojan) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Shadowsocks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shadowsocks) Reset() {
	*x = Shadowsocks{}
	mi := &file_common_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shadowsocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shadowsocks) ProtoMessage() {}

func (x *Shadowsocks) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shadowsocks.ProtoReflect.Descriptor instead.
func (*Shadowsocks) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{19}
}

func (x *Shadowsocks) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Shadowsocks) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type Wireguard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PeerIps       []string               `protobuf:"bytes,2,rep,name=peer_ips,json=peerIps,proto3" json:"peer_ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wireguard) Reset() {
	*x = Wireguard{}
	mi := &file_common_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wireguard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wireguard) ProtoMessage() {}

func (x *Wireguard) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wireguard.ProtoReflect.Descriptor instead.
func (*Wireguard) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{20}
}

func (x *Wireguard) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Wireguard) GetPeerIps() []string {
	if x != nil {
		return x.PeerIps
	}
	return nil
}

type Hysteria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          string                 `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hysteria) Reset() {
	*x = Hysteria{}
	mi := &file_common_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hysteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hysteria) ProtoMessage() {}

func (x *Hysteria) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hysteria.ProtoReflect.Descriptor instead.
func (*Hysteria) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{21}
}

func (x *Hysteria) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type Proxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vmess         *Vmess                 `protobuf:"bytes,1,opt,name=vmess,proto3" json:"vmess,omitempty"`
	Vless         *Vless                 `protobuf:"bytes,2,opt,name=vless,proto3" json:"vless,omitempty"`
	Trojan        *Trojan                `protobuf:"bytes,3,opt,name=trojan,proto3" json:"trojan,omitempty"`
	Shadowsocks   *Shadowsocks           `protobuf:"bytes,4,opt,name=shadowsocks,proto3" json:"shadowsocks,omitempty"`
	Wireguard     *Wireguard             `protobuf:"bytes,5,opt,name=wireguard,proto3" json:"wireguard,omitempty"`
	Hysteria      *Hysteria              `protobuf:"bytes,6,opt,name=hysteria,proto3" json:"hysteria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proxy) Reset() {
	*x = Proxy{}
	mi := &file_common_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxy) ProtoMessage() {}

func (x *Proxy) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxy.ProtoReflect.Descriptor instead.
func (*Proxy) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{22}
}

func (x *Proxy) GetVmess() *Vmess {
	if x != nil {
		return x.Vmess
	}
	return nil
}

func (x *Proxy) GetVless() *Vless {
	if x != nil {
		return x.Vless
	}
	return nil
}

func (x *Proxy) GetTrojan() *Trojan {
	if x != nil {
		return x.Trojan
	}
	return nil
}

func (x *Proxy) GetShadowsocks() *Shadowsocks {
	if x != nil {
		return x.Shadowsocks
	}
	return nil
}

func (x *Proxy) GetWireguard() *Wireguard {
	if x != nil {
		return x.Wireguard
	}
	return nil
}

func (x *Proxy) GetHysteria() *Hysteria {
	if x != nil {
		return x.Hysteria
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Proxies       *Proxy                 `protobuf:"bytes,2,opt,name=proxies,proto3" json:"proxies,omitempty"`
	Inbounds      []string               `protobuf:"bytes,3,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_common_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{23}
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetProxies() *Proxy {
	if x != nil {
		return x.Proxies
	}
	return nil
}

func (x *User) GetInbounds() []string {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_common_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{24}
}

func (x *Users) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UsersChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Last          bool                   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersChunk) Reset() {
	*x = UsersChunk{}
	mi := &file_common_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersChunk) ProtoMessage() {}

func (x *UsersChunk) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersChunk.ProtoReflect.Descriptor instead.
func (*UsersChunk) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{25}
}

func (x *UsersChunk) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UsersChunk) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *UsersChunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

// Routing (mirrors xray app/router/command, node-friendly shapes)
type RoutingRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutboundTag   string                 `protobuf:"bytes,1,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	RuleTag       string                 `protobuf:"bytes,2,opt,name=rule_tag,json=ruleTag,proto3" json:"rule_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingRule) Reset() {
	*x = RoutingRule{}
	mi := &file_common_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingRule) ProtoMessage() {}

func (x *RoutingRule) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingRule.ProtoReflect.Descriptor instead.
func (*RoutingRule) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{26}
}

func (x *RoutingRule) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

func (x *RoutingRule) GetRuleTag() string {
	if x != nil {
		return x.RuleTag
	}
	return ""
}

type RoutingRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*RoutingRule         `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingRulesResponse) Reset() {
	*x = RoutingRulesResponse{}
	mi := &file_common_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingRulesResponse) ProtoMessage() {}

func (x *RoutingRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingRulesResponse.ProtoReflect.Descriptor instead.
func (*RoutingRulesResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{27}
}

func (x *RoutingRulesResponse) GetRules() []*RoutingRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type BalancerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalancerInfoRequest) Reset() {
	*x = BalancerInfoRequest{}
	mi := &file_common_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalancerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalancerInfoRequest) ProtoMessage() {}

func (x *BalancerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalancerInfoRequest.ProtoReflect.Descriptor instead.
func (*BalancerInfoRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{28}
}

func (x *BalancerInfoRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type BalancerInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OverrideTarget  string                 `protobuf:"bytes,1,opt,name=override_target,json=overrideTarget,proto3" json:"override_target,omitempty"`
	PrincipleTarget []string               `protobuf:"bytes,2,rep,name=principle_target,json=principleTarget,proto3" json:"principle_target,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BalancerInfoResponse) Reset() {
	*x = BalancerInfoResponse{}
	mi := &file_common_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalancerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalancerInfoResponse) ProtoMessage() {}

func (x *BalancerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalancerInfoResponse.ProtoReflect.Descriptor instead.
func (*BalancerInfoResponse) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{29}
}

func (x *BalancerInfoResponse) GetOverrideTarget() string {
	if x != nil {
		return x.OverrideTarget
	}
	return ""
}

func (x *BalancerInfoResponse) GetPrincipleTarget() []string {
	if x != nil {
		return x.PrincipleTarget
	}
	return nil
}

type TestRouteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InboundTag     string                 `protobuf:"bytes,1,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	Network        string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"` // "tcp" | "udp"
	TargetIp       string                 `protobuf:"bytes,3,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	TargetDomain   string                 `protobuf:"bytes,4,opt,name=target_domain,json=targetDomain,proto3" json:"target_domain,omitempty"`
	TargetPort     uint32                 `protobuf:"varint,5,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Protocol       string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	User           string                 `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	Attributes     map[string]string      `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FieldSelectors []string               `protobuf:"bytes,9,rep,name=field_selectors,json=fieldSelectors,proto3" json:"field_selectors,omitempty"`
	PublishResult  bool                   `protobuf:"varint,10,opt,name=publish_result,json=publishResult,proto3" json:"publish_result,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestRouteRequest) Reset() {
	*x = TestRouteRequest{}
	mi := &file_common_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRouteRequest) ProtoMessage() {}

func (x *TestRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRouteRequest.ProtoReflect.Descriptor instead.
func (*TestRouteRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{30}
}

func (x *TestRouteRequest) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *TestRouteRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *TestRouteRequest) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *TestRouteRequest) GetTargetDomain() string {
	if x != nil {
		return x.TargetDomain
	}
	return ""
}

func (x *TestRouteRequest) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *TestRouteRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TestRouteRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *TestRouteRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *TestRouteRequest) GetFieldSelectors() []string {
	if x != nil {
		return x.FieldSelectors
	}
	return nil
}

func (x *TestRouteRequest) GetPublishResult() bool {
	if x != nil {
		return x.PublishResult
	}
	return false
}

type RouteResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OutboundTag       string                 `protobuf:"bytes,1,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	OutboundGroupTags []string               `protobuf:"bytes,2,rep,name=outbound_group_tags,json=outboundGroupTags,proto3" json:"outbound_group_tags,omitempty"`
	InboundTag        string                 `protobuf:"bytes,3,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	Network           string                 `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	TargetDomain      string                 `protobuf:"bytes,5,opt,name=target_domain,json=targetDomain,proto3" json:"target_domain,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RouteResult) Reset() {
	*x = RouteResult{}
	mi := &file_common_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResult) ProtoMessage() {}

func (x *RouteResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResult.ProtoReflect.Descriptor instead.
func (*RouteResult) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{31}
}

func (x *RouteResult) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

func (x *RouteResult) GetOutboundGroupTags() []string {
	if x != nil {
		return x.OutboundGroupTags
	}
	return nil
}

func (x *RouteResult) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *RouteResult) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *RouteResult) GetTargetDomain() string {
	if x != nil {
		return x.TargetDomain
	}
	return ""
}

type AddRoutingRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Rule  string                 `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"` // JSON for one xray routing rule (same shape as routing.rules[])
	// false (default) appends the rule, keeping existing rules; true resets the
	// router (clears all rules + balancers) before adding. Default is the safe,
	// non-destructive behavior.
	ShouldReset   bool `protobuf:"varint,2,opt,name=should_reset,json=shouldReset,proto3" json:"should_reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRoutingRuleRequest) Reset() {
	*x = AddRoutingRuleRequest{}
	mi := &file_common_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRoutingRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoutingRuleRequest) ProtoMessage() {}

func (x *AddRoutingRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoutingRuleRequest.ProtoReflect.Descriptor instead.
func (*AddRoutingRuleRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{32}
}

func (x *AddRoutingRuleRequest) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *AddRoutingRuleRequest) GetShouldReset() bool {
	if x != nil {
		return x.ShouldReset
	}
	return false
}

type RemoveRoutingRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleTag       string                 `protobuf:"bytes,1,opt,name=rule_tag,json=ruleTag,proto3" json:"rule_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoutingRuleRequest) Reset() {
	*x = RemoveRoutingRuleRequest{}
	mi := &file_common_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoutingRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoutingRuleRequest) ProtoMessage() {}

func (x *RemoveRoutingRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoutingRuleRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoutingRuleRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{33}
}

func (x *RemoveRoutingRuleRequest) GetRuleTag() string {
	if x != nil {
		return x.RuleTag
	}
	return ""
}

type OverrideBalancerTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BalancerTag   string                 `protobuf:"bytes,1,opt,name=balancer_tag,json=balancerTag,proto3" json:"balancer_tag,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideBalancerTargetRequest) Reset() {
	*x = OverrideBalancerTargetRequest{}
	mi := &file_common_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideBalancerTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideBalancerTargetRequest) ProtoMessage() {}

func (x *OverrideBalancerTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideBalancerTargetRequest.ProtoReflect.Descriptor instead.
func (*OverrideBalancerTargetRequest) Descriptor() ([]byte, []int) {
	return file_common_service_proto_rawDescGZIP(), []int{34}
}

func (x *OverrideBalancerTargetRequest) GetBalancerTag() string {
	if x != nil {
		return x.BalancerTag
	}
	return ""
}

func (x *OverrideBalancerTargetRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_common_service_proto protoreflect.FileDescriptor

const file_common_service_proto_rawDesc = "" +
	"\n" +
	"\x14common/service.proto\x12\aservice\"\a\n" +
	"\x05Empty\"r\n" +
	"\x10BaseInfoResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12!\n" +
	"\fcore_version\x18\x02 \x01(\tR\vcoreVersion\x12!\n" +
	"\fnode_version\x18\x03 \x01(\tR\vnodeVersion\"\xba\x01\n" +
	"\aBackend\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.service.BackendTypeR\x04type\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12#\n" +
	"\x05users\x18\x03 \x03(\v2\r.service.UserR\x05users\x12\x1d\n" +
	"\n" +
	"keep_alive\x18\x04 \x01(\x04R\tkeepAlive\x12)\n" +
	"\x10exclude_inbounds\x18\x05 \x03(\tR\x0fexcludeInbounds\"\x1d\n" +
	"\x03Log\x12\x16\n" +
	"\x06detail\x18\x01 \x01(\tR\x06detail\"X\n" +
	"\x04Stat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x03R\x05value\"3\n" +
	"\fStatResponse\x12#\n" +
	"\x05stats\x18\x01 \x03(\v2\r.service.StatR\x05stats\"^\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05reset\x18\x02 \x01(\bR\x05reset\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.service.StatTypeR\x04type\">\n" +
	"\x12OnlineStatResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"\xa6\x01\n" +
	"\x19StatsOnlineIpListResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\x03ips\x18\x02 \x03(\v2+.service.StatsOnlineIpListResponse.IpsEntryR\x03ips\x1a6\n" +
	"\bIpsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x19\n" +
	"\x17UsersOnlineStatsRequest\"2\n" +
	"\x18UsersOnlineStatsResponse\x12\x16\n" +
	"\x06emails\x18\x01 \x03(\tR\x06emails\"\xbf\x01\n" +
	"\aLatency\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05alive\x18\x02 \x01(\bR\x05alive\x12\x14\n" +
	"\x05delay\x18\x03 \x01(\x03R\x05delay\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\x12$\n" +
	"\x0elast_seen_time\x18\x05 \x01(\x03R\flastSeenTime\x12\"\n" +
	"\rlast_try_time\x18\x06 \x01(\x03R\vlastTryTime\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\"$\n" +
	"\x0eLatencyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"A\n" +
	"\x0fLatencyResponse\x12.\n" +
	"\tlatencies\x18\x01 \x03(\v2\x10.service.LatencyR\tlatencies\"\xac\x02\n" +
	"\x14BackendStatsResponse\x12#\n" +
	"\rnum_goroutine\x18\x01 \x01(\rR\fnumGoroutine\x12\x15\n" +
	"\x06num_gc\x18\x02 \x01(\rR\x05numGc\x12\x14\n" +
	"\x05alloc\x18\x03 \x01(\x04R\x05alloc\x12\x1f\n" +
	"\vtotal_alloc\x18\x04 \x01(\x04R\n" +
	"totalAlloc\x12\x10\n" +
	"\x03sys\x18\x05 \x01(\x04R\x03sys\x12\x18\n" +
	"\amallocs\x18\x06 \x01(\x04R\amallocs\x12\x14\n" +
	"\x05frees\x18\a \x01(\x04R\x05frees\x12!\n" +
	"\flive_objects\x18\b \x01(\x04R\vliveObjects\x12$\n" +
	"\x0epause_total_ns\x18\t \x01(\x04R\fpauseTotalNs\x12\x16\n" +
	"\x06uptime\x18\n" +
	" \x01(\rR\x06uptime\"\x93\x02\n" +
	"\x13SystemStatsResponse\x12\x1b\n" +
	"\tmem_total\x18\x01 \x01(\x04R\bmemTotal\x12\x19\n" +
	"\bmem_used\x18\x02 \x01(\x04R\amemUsed\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\x04R\bcpuCores\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x01R\bcpuUsage\x128\n" +
	"\x18incoming_bandwidth_speed\x18\x05 \x01(\x04R\x16incomingBandwidthSpeed\x128\n" +
	"\x18outgoing_bandwidth_speed\x18\x06 \x01(\x04R\x16outgoingBandwidthSpeed\x12\x16\n" +
	"\x06uptime\x18\a \x01(\x04R\x06uptime\"\x17\n" +
	"\x05Vmess\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x05Vless\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04flow\x18\x02 \x01(\tR\x04flow\"$\n" +
	"\x06Trojan\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"A\n" +
	"\vShadowsocks\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\"E\n" +
	"\tWireguard\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x19\n" +
	"\bpeer_ips\x18\x02 \x03(\tR\apeerIps\"\x1e\n" +
	"\bHysteria\x12\x12\n" +
	"\x04auth\x18\x01 \x01(\tR\x04auth\"\x95\x02\n" +
	"\x05Proxy\x12$\n" +
	"\x05vmess\x18\x01 \x01(\v2\x0e.service.VmessR\x05vmess\x12$\n" +
	"\x05vless\x18\x02 \x01(\v2\x0e.service.VlessR\x05vless\x12'\n" +
	"\x06trojan\x18\x03 \x01(\v2\x0f.service.TrojanR\x06trojan\x126\n" +
	"\vshadowsocks\x18\x04 \x01(\v2\x14.service.ShadowsocksR\vshadowsocks\x120\n" +
	"\twireguard\x18\x05 \x01(\v2\x12.service.WireguardR\twireguard\x12-\n" +
	"\bhysteria\x18\x06 \x01(\v2\x11.service.HysteriaR\bhysteria\"b\n" +
	"\x04User\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12(\n" +
	"\aproxies\x18\x02 \x01(\v2\x0e.service.ProxyR\aproxies\x12\x1a\n" +
	"\binbounds\x18\x03 \x03(\tR\binbounds\",\n" +
	"\x05Users\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.service.UserR\x05users\"[\n" +
	"\n" +
	"UsersChunk\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.service.UserR\x05users\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last\"K\n" +
	"\vRoutingRule\x12!\n" +
	"\foutbound_tag\x18\x01 \x01(\tR\voutboundTag\x12\x19\n" +
	"\brule_tag\x18\x02 \x01(\tR\aruleTag\"B\n" +
	"\x14RoutingRulesResponse\x12*\n" +
	"\x05rules\x18\x01 \x03(\v2\x14.service.RoutingRuleR\x05rules\"'\n" +
	"\x13BalancerInfoRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"j\n" +
	"\x14BalancerInfoResponse\x12'\n" +
	"\x0foverride_target\x18\x01 \x01(\tR\x0eoverrideTarget\x12)\n" +
	"\x10principle_target\x18\x02 \x03(\tR\x0fprincipleTarget\"\xba\x03\n" +
	"\x10TestRouteRequest\x12\x1f\n" +
	"\vinbound_tag\x18\x01 \x01(\tR\n" +
	"inboundTag\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x1b\n" +
	"\ttarget_ip\x18\x03 \x01(\tR\btargetIp\x12#\n" +
	"\rtarget_domain\x18\x04 \x01(\tR\ftargetDomain\x12\x1f\n" +
	"\vtarget_port\x18\x05 \x01(\rR\n" +
	"targetPort\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04user\x18\a \x01(\tR\x04user\x12I\n" +
	"\n" +
	"attributes\x18\b \x03(\v2).service.TestRouteRequest.AttributesEntryR\n" +
	"attributes\x12'\n" +
	"\x0ffield_selectors\x18\t \x03(\tR\x0efieldSelectors\x12%\n" +
	"\x0epublish_result\x18\n" +
	" \x01(\bR\rpublishResult\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x01\n" +
	"\vRouteResult\x12!\n" +
	"\foutbound_tag\x18\x01 \x01(\tR\voutboundTag\x12.\n" +
	"\x13outbound_group_tags\x18\x02 \x03(\tR\x11outboundGroupTags\x12\x1f\n" +
	"\vinbound_tag\x18\x03 \x01(\tR\n" +
	"inboundTag\x12\x18\n" +
	"\anetwork\x18\x04 \x01(\tR\anetwork\x12#\n" +
	"\rtarget_domain\x18\x05 \x01(\tR\ftargetDomain\"N\n" +
	"\x15AddRoutingRuleRequest\x12\x12\n" +
	"\x04rule\x18\x01 \x01(\tR\x04rule\x12!\n" +
	"\fshould_reset\x18\x02 \x01(\bR\vshouldReset\"5\n" +
	"\x18RemoveRoutingRuleRequest\x12\x19\n" +
	"\brule_tag\x18\x01 \x01(\tR\aruleTag\"Z\n" +
	"\x1dOverrideBalancerTargetRequest\x12!\n" +
	"\fbalancer_tag\x18\x01 \x01(\tR\vbalancerTag\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target*&\n" +
	"\vBackendType\x12\b\n" +
	"\x04XRAY\x10\x00\x12\r\n" +
	"\tWIREGUARD\x10\x01*_\n" +
	"\bStatType\x12\r\n" +
	"\tOutbounds\x10\x00\x12\f\n" +
	"\bOutbound\x10\x01\x12\f\n" +
	"\bInbounds\x10\x02\x12\v\n" +
	"\aInbound\x10\x03\x12\r\n" +
	"\tUsersStat\x10\x04\x12\f\n" +
	"\bUserStat\x10\x052\xba\n" +
	"\n" +
	"\vNodeService\x126\n" +
	"\x05Start\x12\x10.service.Backend\x1a\x19.service.BaseInfoResponse\"\x00\x12(\n" +
	"\x04Stop\x12\x0e.service.Empty\x1a\x0e.service.Empty\"\x00\x12:\n" +
	"\vGetBaseInfo\x12\x0e.service.Empty\x1a\x19.service.BaseInfoResponse\"\x00\x12+\n" +
	"\aGetLogs\x12\x0e.service.Empty\x1a\f.service.Log\"\x000\x01\x12@\n" +
	"\x0eGetSystemStats\x12\x0e.service.Empty\x1a\x1c.service.SystemStatsResponse\"\x00\x12B\n" +
	"\x0fGetBackendStats\x12\x0e.service.Empty\x1a\x1d.service.BackendStatsResponse\"\x00\x129\n" +
	"\bGetStats\x12\x14.service.StatRequest\x1a\x15.service.StatResponse\"\x00\x12J\n" +
	"\x13GetOutboundsLatency\x12\x17.service.LatencyRequest\x1a\x18.service.LatencyResponse\"\x00\x12I\n" +
	"\x12GetUserOnlineStats\x12\x14.service.StatRequest\x1a\x1b.service.OnlineStatResponse\"\x00\x12V\n" +
	"\x18GetUserOnlineIpListStats\x12\x14.service.StatRequest\x1a\".service.StatsOnlineIpListResponse\"\x00\x12\\\n" +
	"\x13GetUsersOnlineStats\x12 .service.UsersOnlineStatsRequest\x1a!.service.UsersOnlineStatsResponse\"\x00\x12-\n" +
	"\bSyncUser\x12\r.service.User\x1a\x0e.service.Empty\"\x00(\x01\x12-\n" +
	"\tSyncUsers\x12\x0e.service.Users\x1a\x0e.service.Empty\"\x00\x12;\n" +
	"\x10SyncUsersChunked\x12\x13.service.UsersChunk\x1a\x0e.service.Empty\"\x00(\x01\x12C\n" +
	"\x10ListRoutingRules\x12\x0e.service.Empty\x1a\x1d.service.RoutingRulesResponse\"\x00\x12P\n" +
	"\x0fGetBalancerInfo\x12\x1c.service.BalancerInfoRequest\x1a\x1d.service.BalancerInfoResponse\"\x00\x12>\n" +
	"\tTestRoute\x12\x19.service.TestRouteRequest\x1a\x14.service.RouteResult\"\x00\x12B\n" +
	"\x0eAddRoutingRule\x12\x1e.service.AddRoutingRuleRequest\x1a\x0e.service.Empty\"\x00\x12H\n" +
	"\x11RemoveRoutingRule\x12!.service.RemoveRoutingRuleRequest\x1a\x0e.service.Empty\"\x00\x12R\n" +
	"\x16OverrideBalancerTarget\x12&.service.OverrideBalancerTargetRequest\x1a\x0e.service.Empty\"\x00B#Z!github.com/pasarguard/node/commonb\x06proto3"

var (
	file_common_service_proto_rawDescOnce sync.Once
	file_common_service_proto_rawDescData []byte
)

func file_common_service_proto_rawDescGZIP() []byte {
	file_common_service_proto_rawDescOnce.Do(func() {
		file_common_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_service_proto_rawDesc), len(file_common_service_proto_rawDesc)))
	})
	return file_common_service_proto_rawDescData
}

var file_common_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_service_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_common_service_proto_goTypes = []any{
	(BackendType)(0),                      // 0: service.BackendType
	(StatType)(0),                         // 1: service.StatType
	(*Empty)(nil),                         // 2: service.Empty
	(*BaseInfoResponse)(nil),              // 3: service.BaseInfoResponse
	(*Backend)(nil),                       // 4: service.Backend
	(*Log)(nil),                           // 5: service.Log
	(*Stat)(nil),                          // 6: service.Stat
	(*StatResponse)(nil),                  // 7: service.StatResponse
	(*StatRequest)(nil),                   // 8: service.StatRequest
	(*OnlineStatResponse)(nil),            // 9: service.OnlineStatResponse
	(*StatsOnlineIpListResponse)(nil),     // 10: service.StatsOnlineIpListResponse
	(*UsersOnlineStatsRequest)(nil),       // 11: service.UsersOnlineStatsRequest
	(*UsersOnlineStatsResponse)(nil),      // 12: service.UsersOnlineStatsResponse
	(*Latency)(nil),                       // 13: service.Latency
	(*LatencyRequest)(nil),                // 14: service.LatencyRequest
	(*LatencyResponse)(nil),               // 15: service.LatencyResponse
	(*BackendStatsResponse)(nil),          // 16: service.BackendStatsResponse
	(*SystemStatsResponse)(nil),           // 17: service.SystemStatsResponse
	(*Vmess)(nil),                         // 18: service.Vmess
	(*Vless)(nil),                         // 19: service.Vless
	(*Trojan)(nil),                        // 20: service.Trojan
	(*Shadowsocks)(nil),                   // 21: service.Shadowsocks
	(*Wireguard)(nil),                     // 22: service.Wireguard
	(*Hysteria)(nil),                      // 23: service.Hysteria
	(*Proxy)(nil),                         // 24: service.Proxy
	(*User)(nil),                          // 25: service.User
	(*Users)(nil),                         // 26: service.Users
	(*UsersChunk)(nil),                    // 27: service.UsersChunk
	(*RoutingRule)(nil),                   // 28: service.RoutingRule
	(*RoutingRulesResponse)(nil),          // 29: service.RoutingRulesResponse
	(*BalancerInfoRequest)(nil),           // 30: service.BalancerInfoRequest
	(*BalancerInfoResponse)(nil),          // 31: service.BalancerInfoResponse
	(*TestRouteRequest)(nil),              // 32: service.TestRouteRequest
	(*RouteResult)(nil),                   // 33: service.RouteResult
	(*AddRoutingRuleRequest)(nil),         // 34: service.AddRoutingRuleRequest
	(*RemoveRoutingRuleRequest)(nil),      // 35: service.RemoveRoutingRuleRequest
	(*OverrideBalancerTargetRequest)(nil), // 36: service.OverrideBalancerTargetRequest
	nil,                                   // 37: service.StatsOnlineIpListResponse.IpsEntry
	nil,                                   // 38: service.TestRouteRequest.AttributesEntry
}
var file_common_service_proto_depIdxs = []int32{
	0,  // 0: service.Backend.type:type_name -> service.BackendType
	25, // 1: service.Backend.users:type_name -> service.User
	6,  // 2: service.StatResponse.stats:type_name -> service.Stat
	1,  // 3: service.StatRequest.type:type_name -> service.StatType
	37, // 4: service.StatsOnlineIpListResponse.ips:type_name -> service.StatsOnlineIpListResponse.IpsEntry
	13, // 5: service.LatencyResponse.latencies:type_name -> service.Latency
	18, // 6: service.Proxy.vmess:type_name -> service.Vmess
	19, // 7: service.Proxy.vless:type_name -> service.Vless
	20, // 8: service.Proxy.trojan:type_name -> service.Trojan
	21, // 9: service.Proxy.shadowsocks:type_name -> service.Shadowsocks
	22, // 10: service.Proxy.wireguard:type_name -> service.Wireguard
	23, // 11: service.Proxy.hysteria:type_name -> service.Hysteria
	24, // 12: service.User.proxies:type_name -> service.Proxy
	25, // 13: service.Users.users:type_name -> service.User
	25, // 14: service.UsersChunk.users:type_name -> service.User
	28, // 15: service.RoutingRulesResponse.rules:type_name -> service.RoutingRule
	38, // 16: service.TestRouteRequest.attributes:type_name -> service.TestRouteRequest.AttributesEntry
	4,  // 17: service.NodeService.Start:input_type -> service.Backend
	2,  // 18: service.NodeService.Stop:input_type -> service.Empty
	2,  // 19: service.NodeService.GetBaseInfo:input_type -> service.Empty
	2,  // 20: service.NodeService.GetLogs:input_type -> service.Empty
	2,  // 21: service.NodeService.GetSystemStats:input_type -> service.Empty
	2,  // 22: service.NodeService.GetBackendStats:input_type -> service.Empty
	8,  // 23: service.NodeService.GetStats:input_type -> service.StatRequest
	14, // 24: service.NodeService.GetOutboundsLatency:input_type -> service.LatencyRequest
	8,  // 25: service.NodeService.GetUserOnlineStats:input_type -> service.StatRequest
	8,  // 26: service.NodeService.GetUserOnlineIpListStats:input_type -> service.StatRequest
	11, // 27: service.NodeService.GetUsersOnlineStats:input_type -> service.UsersOnlineStatsRequest
	25, // 28: service.NodeService.SyncUser:input_type -> service.User
	26, // 29: service.NodeService.SyncUsers:input_type -> service.Users
	27, // 30: service.NodeService.SyncUsersChunked:input_type -> service.UsersChunk
	2,  // 31: service.NodeService.ListRoutingRules:input_type -> service.Empty
	30, // 32: service.NodeService.GetBalancerInfo:input_type -> service.BalancerInfoRequest
	32, // 33: service.NodeService.TestRoute:input_type -> service.TestRouteRequest
	34, // 34: service.NodeService.AddRoutingRule:input_type -> service.AddRoutingRuleRequest
	35, // 35: service.NodeService.RemoveRoutingRule:input_type -> service.RemoveRoutingRuleRequest
	36, // 36: service.NodeService.OverrideBalancerTarget:input_type -> service.OverrideBalancerTargetRequest
	3,  // 37: service.NodeService.Start:output_type -> service.BaseInfoResponse
	2,  // 38: service.NodeService.Stop:output_type -> service.Empty
	3,  // 39: service.NodeService.GetBaseInfo:output_type -> service.BaseInfoResponse
	5,  // 40: service.NodeService.GetLogs:output_type -> service.Log
	17, // 41: service.NodeService.GetSystemStats:output_type -> service.SystemStatsResponse
	16, // 42: service.NodeService.GetBackendStats:output_type -> service.BackendStatsResponse
	7,  // 43: service.NodeService.GetStats:output_type -> service.StatResponse
	15, // 44: service.NodeService.GetOutboundsLatency:output_type -> service.LatencyResponse
	9,  // 45: service.NodeService.GetUserOnlineStats:output_type -> service.OnlineStatResponse
	10, // 46: service.NodeService.GetUserOnlineIpListStats:output_type -> service.StatsOnlineIpListResponse
	12, // 47: service.NodeService.GetUsersOnlineStats:output_type -> service.UsersOnlineStatsResponse
	2,  // 48: service.NodeService.SyncUser:output_type -> service.Empty
	2,  // 49: service.NodeService.SyncUsers:output_type -> service.Empty
	2,  // 50: service.NodeService.SyncUsersChunked:output_type -> service.Empty
	29, // 51: service.NodeService.ListRoutingRules:output_type -> service.RoutingRulesResponse
	31, // 52: service.NodeService.GetBalancerInfo:output_type -> service.BalancerInfoResponse
	33, // 53: service.NodeService.TestRoute:output_type -> service.RouteResult
	2,  // 54: service.NodeService.AddRoutingRule:output_type -> service.Empty
	2,  // 55: service.NodeService.RemoveRoutingRule:output_type -> service.Empty
	2,  // 56: service.NodeService.OverrideBalancerTarget:output_type -> service.Empty
	37, // [37:57] is the sub-list for method output_type
	17, // [17:37] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_common_service_proto_init() }
func file_common_service_proto_init() {
	if File_common_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_service_proto_rawDesc), len(file_common_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_service_proto_goTypes,
		DependencyIndexes: file_common_service_proto_depIdxs,
		EnumInfos:         file_common_service_proto_enumTypes,
		MessageInfos:      file_common_service_proto_msgTypes,
	}.Build()
	File_common_service_proto = out.File
	file_common_service_proto_goTypes = nil
	file_common_service_proto_depIdxs = nil
}
